name: voila
channels:
    - conda-forge
dependencies:
    - python==3.9.13
    - ipython==8.12.0
    - pandas==1.5.1
    - plotly==5.11.0
    - openpyxl==3.0.10
    - ipywidgets==8.0.6
    - voila==0.3.7
    - nodejs
    - nbgitpuller==1.1.1
    - scikit-learn==1.2.2
    - scipy==1.9.1
    - lxml-html-clean